[2024-09-01T02:10:41.635+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-01T02:10:41.683+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_oto_dag.modify_data manual__2024-08-31T18:24:53.160308+00:00 [queued]>
[2024-09-01T02:10:41.700+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_oto_dag.modify_data manual__2024-08-31T18:24:53.160308+00:00 [queued]>
[2024-09-01T02:10:41.700+0700] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-09-01T02:10:41.723+0700] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): modify_data> on 2024-08-31 18:24:53.160308+00:00
[2024-09-01T02:10:41.736+0700] {standard_task_runner.py:64} INFO - Started process 129001 to run task
[2024-09-01T02:10:41.744+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'scrap_oto_dag', 'modify_data', 'manual__2024-08-31T18:24:53.160308+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/oto/scrap_oto.py', '--cfg-path', '/tmp/tmp7myzi70o']
[2024-09-01T02:10:41.749+0700] {standard_task_runner.py:91} INFO - Job 172: Subtask modify_data
[2024-09-01T02:10:41.862+0700] {task_command.py:426} INFO - Running <TaskInstance: scrap_oto_dag.modify_data manual__2024-08-31T18:24:53.160308+00:00 [running]> on host BrightHorizons.
[2024-09-01T02:10:42.063+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrap_oto_dag' AIRFLOW_CTX_TASK_ID='modify_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T18:24:53.160308+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T18:24:53.160308+00:00'
[2024-09-01T02:10:42.066+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-01T02:10:42.109+0700] {base.py:84} INFO - Using connection ID 'spark_local' for task execution.
[2024-09-01T02:10:42.111+0700] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master local[*] --name arrow-spark --deploy-mode client /home/miracle/mobil/spark_transform/transform.py
[2024-09-01T02:10:44.782+0700] {spark_submit.py:579} INFO - 24/09/01 02:10:44 WARN Utils: Your hostname, BrightHorizons resolves to a loopback address: 127.0.1.1; using 10.255.255.254 instead (on interface lo)
[2024-09-01T02:10:44.786+0700] {spark_submit.py:579} INFO - 24/09/01 02:10:44 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-09-01T02:10:45.501+0700] {spark_submit.py:579} INFO - python3: can't open file '/home/miracle/mobil/spark_transform/transform.py': [Errno 2] No such file or directory
[2024-09-01T02:10:45.522+0700] {spark_submit.py:579} INFO - 24/09/01 02:10:45 INFO ShutdownHookManager: Shutdown hook called
[2024-09-01T02:10:45.524+0700] {spark_submit.py:579} INFO - 24/09/01 02:10:45 INFO ShutdownHookManager: Deleting directory /tmp/spark-8b191e94-b5ef-4133-add1-a58cb2e5dfc1
[2024-09-01T02:10:45.556+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-01T02:10:45.572+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master local[*] --name arrow-spark --deploy-mode client /home/miracle/mobil/spark_transform/transform.py. Error code is: 2.
[2024-09-01T02:10:45.575+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=scrap_oto_dag, task_id=modify_data, run_id=manual__2024-08-31T18:24:53.160308+00:00, execution_date=20240831T182453, start_date=20240831T191041, end_date=20240831T191045
[2024-09-01T02:10:45.592+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 172 for task modify_data (Cannot execute: spark-submit --master local[*] --name arrow-spark --deploy-mode client /home/miracle/mobil/spark_transform/transform.py. Error code is: 2.; 129001)
[2024-09-01T02:10:45.619+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-09-01T02:10:45.655+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T02:10:45.657+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
